export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const FETCH_ADMINS = 'FETCH_ADMINS';
export const FETCH_ADMIN = 'FETCH_ADMIN';
export const CREATE_ADMIN = 'CREATE_ADMIN';
export const EDIT_ADMIN = 'EDIT_ADMIN';
export const DELETE_ADMIN = 'DELETE_ADMIN';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const FETCH_FLIGHT = 'FETCH_FLGIHT';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const EDIT_FLIGHT = 'EDIT_FLIGHT';

export const CREATE_AIRLINER = 'CREATE_AIRLINER';
export const FETCH_AIRLINERS = 'FETCH_AIRLINERS';
export const FETCH_AIRLINER = 'FETCH_AIRLINER';
export const DELETE_AIRLINER = 'DELETE_AIRLINER';
export const EDIT_AIRLINER = 'EDIT_AIRLINER';

export const FETCH_AIRPORTS = 'FETCH_AIRPORTS';
export const FETCH_AIRPORT = 'FETCH_AIRPORT';
export const CREATE_AIRPORT = 'CREATE_AIRPORT';
export const EDIT_AIRPORT = 'EDIT_AIRPORT';
export const DELETE_AIRPORT = 'DELETE_AIRPORT';

export const FETCH_BOOKINGS = 'FETCH_BOOKINGS';
export const DELETE_BOOKING = 'DELETE_BOOKINGS';
export const CLEAR_BOOKINGS = 'CLEAR_BOOKINGS';